on: [push]
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Vitest Coverage Report
  # You may pin to the exact commit or the version.
  # uses: davelosert/vitest-coverage-report-action@e93ba7d37d24899cc65c5525a1eefd89ae5cf365
        uses: davelosert/vitest-coverage-report-action@v2.2.1
