on: [push]
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: 'Install Deps'
      run: npm install
    - name: 'Test'
      run: npx vitest
    - name: 'Report Coverage'
      # Set if: always() to also generate the report if tests are failing
      # Only works if you set `reportOnFailure: true` in your vite config as specified above
      run: cat /home/runner/work/VIHU_assignment_2/VIHU_assignment_2/coverage/coverage-summary.json
